### ISSUE TITLE
AxiosError: Request failed with status code 400 when fetching tokens

### ISSUE THREAD

**Issue by rabbitshu** [d01000100/figma-token-engine#58]
Hi!

Firstly, thanks for the package – it's been really handy! I was using it for some time and everything was smooth. However, a few weeks ago, an error started appearing.

When I attempt to fetch tokens, this error shows up: "AxiosError: Request failed with status code 400".

I've tried to regenerate Figma access token but it didn't help.
Notably, I can still upload tokens using the Tokens Studio plugin in Figma to my GitHub repository without any issues. You can find them here: [tokens.json](https://github.com/rabbitshu/2-figma/blob/main/tokens.json).

Here's my .tokens.config.json:
```
{
  "tokenFormat": "TokensStudio",
  "figmaFileId": "",
  "inputFile": "./tokens-studio.json",
  "outputDir": "./src/constants",
  "platforms": ["ts"]
}
```
Error logs:
```
[15:05:23.439 - Event] Start Figma Token Engine
[15:05:23.439 - Event] Figma Tokens
[15:05:23.439 - Event] Figma API - Get Figma API Credentials
✅ FIGMA_PERSONAL_ACCESS_TOKEN in .env
✅ FIGMA_FILE_URL in .env
[15:05:23.440 - Event] Figma API - Get Figma File Plugin Data
🌏  Fetch Figma API

[15:06:19.782 - Error] AxiosError: Request failed with status code 400 

/Users/rabbitshu/projects/2s-app/node_modules/figma-token-engine/build/utils/logger.js:38
    throw new Error(str);
          ^

Error: AxiosError: Request failed with status code 400
    at logError (/Users/rabbitshu/projects/2s-app/node_modules/figma-token-engine/build/utils/logger.js:38:11)
    at getFigmaFilePluginsData (/Users/rabbitshu/projects/2s-app/node_modules/figma-token-engine/build/figma-api/services.js:37:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getTokensStudio (/Users/rabbitshu/projects/2s-app/node_modules/figma-token-engine/build/figma-api/index.js:15:30)
    at async processTokensStudio (/Users/rabbitshu/projects/2s-app/node_modules/figma-token-engine/build/tokens-studio/index.js:12:11)
    at async runTokenEngine (/Users/rabbitshu/projects/2s-app/node_modules/figma-token-engine/build/index.js:55:9)
```

Environment: Node.js v18.15.0

I'm stumped about what's causing this. Any insights or help would be much appreciated. Thank you!

**Comment by d01000100** [comment]
The error triggers when the FTE tries to communicate to Figma for the tokens. According to [Figma API docs](https://www.figma.com/developers/api#errors):

> 400
> Bad request
> Parameters are invalid or malformed. Please check the input formats. This error can also happen if the requested resources are too large to complete the request, which results in a timeout. Please reduce the number and size of objects requested.

Check the `.env` variables, specifically the `FIGMA_FILE_URL` ¿is it the correct link? It should be the complete file link: `https://www.figma.com/file/d7ihCE0mWwfGBUR3ECop8z/` or just the file id: `d7ihCE0mWwfGBUR3ECop8z`

---- 

I tried to replicate the error with a new file with your same tokens and I could fetch them. I tried modifying the `FIGMA_FILE_URL` myself but I got **404** errors instead, so idk if it's a specific error with your URL

**Comment by rabbitshu** [comment]
Thank you for getting back to me.

After spending some time with the Figma API, I've come to realize that the root of the error is tied to the extensive structure of my design file. While I don't have a vast number of tokens, the API request was pulling in a significant amount of extraneous design data. By setting a depth limit on the response, I was able to eliminate the error. This adjustment should also enhance the response time.

I've opened pull request #59 for this. Would appreciate it if you could review the changes. Thanks!

**Comment by rabbitshu** [comment]
Thank you for your support!
